export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAILURE = "FETCH_BOOKINGS_FAILURE";
export const FETCH_SINGLE_BOOKING_REQUEST = "FETCH_SINGLE_BOOKING_REQUEST";
export const FETCH_SINGLE_BOOKING_SUCCESS = "FETCH_SINGLE_BOOKING_SUCCESS";
export const FETCH_SINGLE_BOOKING_FAILURE = "FETCH_SINGLE_BOOKING_FAILURE";