export const FETCH_HOMES_REQUEST = "FETCH_HOMES_REQUEST";
export const FETCH_HOMES_SUCCESS = "FETCH_HOMES_SUCCESS";
export const FETCH_HOMES_FAILURE = "FETCH_HOMES_FAILURE";
export const FETCH_SINGLE_HOME_REQUEST = "FETCH_SINGLE_HOME_REQUEST";
export const FETCH_SINGLE_HOME_SUCCESS = "FETCH_SINGLE_HOME_SUCCESS";
export const FETCH_SINGLE_HOME_FAILURE = "FETCH_SINGLE_HOME_FAILURE";