export const REGISTER_TOURIST_REQUEST = "REGISTER_TOURIST_REQUEST";
export const REGISTER_TOURIST_SUCCESS = "REGISTER_TOURIST_SUCCESS";
export const REGISTER_TOURIST_FAILURE = "REGISTER_TOURIST_FAILURE";
export const LOGIN_TOURIST_REQUEST = "LOGIN_TOURIST_REQUEST";
export const LOGIN_TOURIST_SUCCESS = "LOGIN_TOURIST_SUCCESS";
export const LOGIN_TOURIST_FAILURE = "LOGIN_TOURIST_FAILURE";